== Lab {counter:labs}: Stock pricing with UDF

Consider a topic of stock price events that you want to calculate the volume-weighted average price (VWAP) for each event, publishing the result to a new topic.
There is no built-in function for VWAP, so we'll write a custom ksqlDB UDF that performs the calculation.
see [official tutorial](https://kafka-tutorials.confluent.io/udf/ksql.html?_ga=2.223343775.583678155.1587977444-275217082.1587977444)
link:https://kafka-tutorials.confluent.io/udf/ksql.html?_ga=2.223343775.583678155.1587977444-275217082.1587977444[official tutorial, window=_blank]

In our workshop the UDF is already prepared for you and linked into ksqlDB. Please see the tutorial description and check proceedings.

Start the ksqlDB CLI if is not already running:-

[IMPORTANT]
====
[source,subs="attributes"]
----
docker exec -it ksqldb-cli ksql http://ksqldb-server-onprem:8088
----
====

List the available functions

[source,subs="attributes"]
----
SHOW FUNCTIONS;
----

Inspect the VWAP function:-

[source,subs="attributes"]
----
DESCRIBE FUNCTION VWAP;
----

Create the stream `raw_quotes`

[IMPORTANT]
====
[source,subs="quotes,attributes"]
----
*CREATE STREAM* raw_quotes(ticker varchar key, bid int, ask int, bidqty int, askqty int) *WITH*(kafka_topic='stockquotes', value_format='avro', partitions=1);
----
====

Insert data in the stream `raw_quotes`

[IMPORTANT]
====
[source,subs="quotes,attributes"]
----
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZVV',   25, 35, 100, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZVZZT', 35, 45, 100, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZXZZT', 45, 55, 100, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZTEST', 10, 20, 50, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZVV',   30, 40, 100, 50);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZVZZT', 30, 40, 50, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZXZZT', 50, 60, 100, 50);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZTEST', 15, 20, 100, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZVV',   25, 35, 100, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZVZZT', 35, 45, 100, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZXZZT', 45, 55, 100, 100);
INSERT INTO raw_quotes (ticker, bid, ask, bidqty, askqty) VALUES ('ZXZZT', 40, 55, 100, 100);
----
====

See the data in the stream:-

[source,subs="quotes,attributes"]
----
SET 'auto.offset.reset' = 'earliest';
SELECT * FROM raw_quotes EMIT CHANGES LIMIT 12;
----

Now let's test the VWAP function:-

[source,subs="quotes,attributes"]
----
SELECT ticker, vwap(bid, bidqty, ask, askqty) AS vwap FROM raw_quotes EMIT CHANGES LIMIT 12;
----

Let's persist the result of the query, so we can use it later

[IMPORTANT]
====
[source,subs="quotes,attributes"]
----
set 'auto.offset.reset'='earliest';
*CREATE STREAM* vwap *WITH* (kafka_topic = 'vwap', partitions = 1) *AS* 
*SELECT*
  ticker,
  vwap(bid, bidqty, ask, askqty) AS vwap
*FROM* raw_quotes
EMIT CHANGES;
----
====

You can inspect the content of newly created topic.

[source,subs="quotes"]
----
PRINT 'vwap' FROM BEGINNING LIMIT 12;
----

Exit the ksqlDB cli 

[IMPORTANT]
====
[source,subs="quotes,attributes"]
----
exit
----
====

